---

- hosts: rpi-kenobi

  vars:
    backup_base_dir: "/root/backups"
    script_source_base: "/data/code/tools/scripts/backup/nas_backups"
    scripts:
      - name: "backup_rpi-kenobi_to_gimli.sh"
        config_folder: "rpi-kenobi"
        configs:
          - "rpi-kenobi_exclude.lst"
          - "rpi-kenobi_files.lst"
          - "restic_rpi-kenobi.pass"
        cron_minute: "0"
        cron_hour: "21"
        cron_disabled: "no"
      - name: "backup_gimli_to_aragorn.sh"
        config_folder: "gimli_to_aragorn"
        configs:
          - "gimli_local.lst"
          - "gimli_local.pass"
        cron_minute: "30"
        cron_hour: "12"
        cron_disabled: "no"
      - name: "backup_gimli_to_b2.sh"
        config_folder: "gimli_to_b2"
        configs:
          - "gimli_to_b2.lst"
          - "gimli_to_b2.pass"
        cron_minute: "0"
        cron_hour: "1"
        cron_day: "*/2"
        cron_disabled: "no"

  tasks:

    - name: Install restic
      pacman:
        name: restic
        state: latest
      become: true
      become_user: root

    - name: Create backups folder
      file:
        path: "{{backup_base_dir}}"
        state: directory
        owner: root
        group: root
      become: true
      become_user: root

    - name: Push script
      template:
        src: "{{ script_source_base }}/{{ item.name }}"
        dest: "{{ backup_base_dir }}"
        owner: root
        group: root
        mode: 0700
        backup: true
      loop: "{{ scripts }}"
      become: true
      become_user: root

    - name: Create config dir
      file:
        path: "{{ backup_base_dir }}/.restic_conf/{{ item.config_folder }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      loop: "{{ scripts }}"
      become: true
      become_user: root

    - name: Push config files
      template:
        src: "{{ script_source_base }}/restic_conf/{{ item.0.config_folder }}/{{ item.1 }}"
        dest: "{{ backup_base_dir }}/.restic_conf/{{ item.0.config_folder }}/{{ item.1 }}"
        owner: root
        group: root
        mode: 0600
        backup: true
      loop: "{{ scripts | subelements( 'configs' ) }}"
      become: true
      become_user: root

    - name: Configure cron
      cron:
        name: "managed backup script: {{ item.name }}"
        job: "flock -n /tmp/backups.lock {{ backup_base_dir }}/{{ item.name }}"
        minute: "{{ item.cron_minute }}"
        hour: "{{ item.cron_hour }}"
        day: "{{ item.cron_day | default('*') }}"
        disabled: "{{ item.cron_disabled }}"
      loop: "{{ scripts }}"
      become: true
      become_user: root
