- hosts: all

  vars:
    directory_cmdb: /tmp/ansible-cmdb
    cmdb_target: /srv/http/cmdb/index.html

  tasks:

  - name: Gather the package facts
    package_facts:
      manager: auto
  
  - name: Copy ansible package facts to a file
    copy:
      content: "{{ ansible_facts.packages }}"
      dest: '{{ directory_cmdb }}/{{ ansible_hostname }}_packages.json'
    delegate_to: localhost

  - name: Copy ansible facts to a file
    copy:
      content: "{{ ansible_facts}}"
      dest: '{{ directory_cmdb }}/{{ ansible_hostname}}_facts.json'
    delegate_to: localhost

  - name: Install ansible-cmdb
    pip:
      name: ansible-cmdb
      state: latest
    become: true
    delegate_to: localhost

  - name: Generate CMDB
    shell:
      cmd: ansible-cmdb --exclude-cols dtap,comment,custom,external_id {{ directory_cmdb }} > {{ cmdb_target }}
    become: true
    delegate_to: localhost

